# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'managed': False, 'ordering': ['start_date']},
        ),
    ]
